basic:
	# "oc基本类型示例"
	clang -framework Foundation basic-demo/basic.m -o basic
flower:
	# "类、协议、实例示例"
	clang -framework Foundation flower-demo/flower.m -o flower
block:
	# "块(Block)示例"
	clang -framework Foundation block-demo/block.m -o block
file:
	# "文件操作示例"
	clang -framework Foundation file-demo/file.m -o file